controller:
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      image:
        repository: registry.k8s.io/ingress-nginx/kube-webhook-certgen
        tag: v20230407
    failurePolicy: Ignore
