version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "9090:8080"   # HostPort:ContainerPort → Jenkins web UI
      - "50000:50000" # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
