apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: windows-exporter
spec:
  selector:
    matchLabels:
      app: windows-exporter
  template:
    metadata:
      labels:
        app: windows-exporter
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: windows-exporter
          image: prometheuscommunity/windows-exporter:latest
          ports:
            - containerPort: 9182
