apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
          - name: MONGO_CONN_STR
            valueFrom:
              secretKeyRef:

                name: mongo-secret
                key: MONGO_CONN_STR
          - name: USE_DB_AUTH
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: USE_DB_AUTH
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_INITDB_ROOT_PASSWORD
