apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: devops-project
type: Opaque
stringData:
  MONGO_CONN_STR: mongodb://mongo-service:27017/admin
  USE_DB_AUTH: "true"
  MONGO_INITDB_ROOT_USERNAME: myUserAdmin
  MONGO_INITDB_ROOT_PASSWORD: securePassword123