apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: techietech/devops-backend:latest
        ports:
        - containerPort: 3500
        env:
        - name: MONGO_CONN_STR
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_CONN_STR
        - name: USE_DB_AUTH
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: USE_DB_AUTH
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
