apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devops-project
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32100
  type: NodePort
