apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: server
  ports:
    - port: 80
      targetPort: 9090
